name: flutteristas
description: flutteristas.com site
repository: https://github.com/TheFlutteristas/flutteristas_website_dev
version: 1.0.0

environment:
  sdk: ^3.1.0

dependencies:
  firebase_dart: ^1.0.11
  firebase_core: ^2.15.0
  firebase_database: ^10.2.5
  jaspr: ^0.9.0
  jaspr_router: ^0.3.0

dev_dependencies:
  build_runner: ^2.4.6
  jaspr_builder: ^0.9.0
  build_web_compilers: ^4.0.6
  lints: ^2.1.1

jaspr:
  uses-ssr: false
