name: flutteristas
description: flutteristas.com site
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

dependencies:
  firebase_dart: ^1.0.11
  jaspr: ^0.8.1
  jaspr_router: ^0.2.3
  firebase_core: ^2.15.0
  firebase_database: ^10.2.5


dev_dependencies:
  build_runner: ^2.4.6
  jaspr_builder: ^0.8.1
  build_web_compilers: ^4.0.5
  lints: ^2.1.1

jaspr:
  uses-ssr: false